### ISSUE TITLE
 Can anyone help me with this error

### ISSUE THREAD

**Issue by LennonPereira** [DSharpPlus/DSharpPlus#1255]
[2022-04-03 16:16:24 -03:00] [108 /WebSocketRec] [Error] Socket handler suppressed an exception
Newtonsoft.Json.JsonSerializationException: Error setting value to 'OAuthFlags' on 'DSharpPlus.Entities.DiscordMember'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordMember.get_User()
   at DSharpPlus.Entities.DiscordMember.set_OAuthFlags(Nullable`1 value)
   at lambda_method166(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at DSharpPlus.Net.Serialization.DiscordJson.ToDiscordObject[T](JToken token)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|391_1(IWebSocketClient sender, SocketMessageEventArgs e)

**Comment by JulianusIV** [comment]
Update to the newest nightly, it should be fixed there

**Comment by OoLunar** [comment]
Confirmed fix as Julianus mentioned above. Nightlies can be found on nuget as pre-releases: https://nuget.org/packages/DSharpPlus

If this does not fix your issue, you're welcome to join our Discord as we'll be able to help you more in-depth in the #support channel.

**Comment by OoLunar** [comment]
That's the latest stable version, which is now mostly non-functional. Please update to the latest nightlies, as they are relatively bug free.

**Comment by LennonPereira** [comment]
How should I proceed to install a version other than the unstable one?

**Comment by OoLunar** [comment]
If you are referring nightlies as unstable, I believe there is a misconception here. Nightlies are the latest commit, which means they include all the latest patches and bug fixes. The only difference between nightlies and stables is that stables are tested more thoroughly before release, while nightlies are only tested for compiler errors. Nightlies also contain all the latest features.

**Comment by LennonPereira** [comment]
Sorry for the difficulty, but I'm really not finding the way to use this latest version. I'm trying through visual studio and it shows that I'm on the latest version.
I tried this command "Install-Package DSharpPlus -Version 4.1.0" but it didn't work either. what should I do?

**Comment by OoLunar** [comment]
> I tried this command "Install-Package DSharpPlus -Version 4.1.0" but it didn't work either.

What do you mean by "didn't work"? Could you give us an error?

> what should I do?

You should install the latest pre-release from our DSharpPlus nuget repository.

**Comment by DWaffles** [comment]
> Sorry for the difficulty, but I'm really not finding the way to use this latest version. I'm trying through visual studio and it shows that I'm on the latest version. I tried this command "Install-Package DSharpPlus -Version 4.1.0" but it didn't work either. what should I do?

The nightlies are pre-releases technically so you'll need to check "include prerelease" or whatever the equivalent for your package manager is.
![devenv_4V14oGsEs6](https://user-images.githubusercontent.com/42708798/161465551-308e7e17-8902-48d6-a9b5-8bc80f2207bd.png)

**Comment by LennonPereira** [comment]
thank you very much it worked
