### ISSUE TITLE
WebSocket problem with members

### ISSUE THREAD

**Issue by D1gitalFox** [DSharpPlus/DSharpPlus#1256]
Sorry for bad english in advance

# Summary
Any time i try to assign a role to someone with `GrantRoleAsync`, it throws a `NullRefereceException` exception despite the fact that both the member and the role exist. It seems that the problem that occurs when the bot starts is the cause

# Details
.NET Framework 5.0
OS: Windows 8.1 (on my PC) and Linux Ubuntu 18.04 (on VPS)
IDE: Visual Studio 2019

Additional info:
- ALL intents are granted in Discord Dev page
- Member and Role i'm trying to grant exists
- The problem remains on 3 different computers

### There are 2 exceptions:
This one is thrown upon starting my bot:
```cs
[2022-04-04 16:00:10 +03:00] [108 /WebSocketRec] [Error] Socket handler suppressed an exception
Newtonsoft.Json.JsonSerializationException: Error setting value to 'OAuthFlags' on 'DSharpPlus.Entities.DiscordMember'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordMember.get_User()
   at DSharpPlus.Entities.DiscordMember.set_OAuthFlags(Nullable`1 value)
   at lambda_method252(Closure , Object , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, Jso
nProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue
, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at DSharpPlus.Net.Serialization.DiscordJson.ToDiscordObject[T](JToken token)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|391_1(IWebSocketClient sender, SocketMessageEventArgs e)
```

And this one when trying to interact with any member (`GrantRoleAsync` for example):
```cs
[04.04.2022 15:54:12.727] [104 /EventHandler] [Error] Event handler exception for event MESSAGE_REACTION_ADDED thrown from System.Threading.
Tasks.Task MessageReactionAdded(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.MessageReactionAddEventArgs) (defined in StarLine.Program)
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordMember.GrantRoleAsync(DiscordRole role, String reason)
   at StarLine.Program.MessageReactionAdded(DiscordClient sender, MessageReactionAddEventArgs e) in Program.cs:line 49
   at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)
```

Program class:
```cs
public static DiscordClient discord;
public static DiscordGuild guild;

private static async Task MainAsync()
{
    discord = new DiscordClient(new DiscordConfiguration
    {
          Intents = DiscordIntents.All, // All intents are granted on discord dev page
          Token = "...",
    });
    discord.MessageReactionAdded += MessageReactionAdded;
    await discord.ConnectAsync();
    guild = await discord.GetGuildAsync(842110386215321650); // This guild exists
    await Task.Delay(-1);
}
```

MessageReactionAdded method:
```cs
private static async Task MessageReactionAdded(DiscordClient sender, MessageReactionAddEventArgs e)
{
    if (e.User.Id == discord.CurrentUser.Id)
        return;
    if (e.Message.Id == 912715082025283644) // This message exists
    {
        DiscordMember member = await guild.GetMemberAsync(e.User.Id); // Changing to "(DiscordMember)e.User" changes nothing
        await member.GrantRoleAsync(guild.GetRole(953673223864729654), "Test reason"); // Exception is on this line. Role exists.
    }
}
```

**Comment by D1gitalFox** [comment]
> update to the latest nightly (01105+)

WebSocket error on starting disappeared, but exception in event remains the same

**Comment by D1gitalFox** [comment]
SORRY, my bad, Role didn't actually existed. But at least it solves problem with Websocket
