### ISSUE TITLE
CreateInteractionResponseAsync randomly throws NotFoundException

### ISSUE THREAD

**Issue by cyclonefreeze** [DSharpPlus/DSharpPlus#1278]
# Summary
I'm not entirely sure how the issue occurs, but sometimes when a user tries to execute a slash command, the bot will throw a NotFoundException that is thrown in CreateInteractionResponseAsync.

# Details
.NET Framework version = .NET 5
Operating system = Windows 11
Changes made = none
IDE = JetBrains Rider 2021.3.3
Exception Type = DSharpPlus.Exceptions.NotFoundException
Exception Message = "Not found: 404"
Stack trace = 
```
DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at DSharpPlus.Net.DiscordApiClient.CreateInteractionResponseAsync(UInt64 interaction_id, String interaction_token, InteractionResponseType type, DiscordInteractionResponseBuilder builder)
   at Pluto.Bot.Modules.User.Manage.GrantAllCosmetics(InteractionContext ctx, DiscordUser discordUser) in C:\Users\cyclonefreeze\Documents\Programming\Pluto\Pluto.Bot\Modules\User.cs:line 156
   at DSharpPlus.SlashCommands.SlashCommandsExtension.RunCommand(BaseContext context, MethodInfo method, IEnumerable`1 args)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass47_0.<<InteractionHandler>b__0>d.MoveNext()
```

Method = 
```
[RequireIds(680481531109572666)]
[SlashCommand("grantAllCosmetics", "Grants all cosmetics to the specified user.")]
public async Task GrantAllCosmetics(InteractionContext ctx,
    [Option("discordUser", "The Discord user linked to the user.")] DiscordUser discordUser)
{
    var user = _internalService.GetUserByDiscordId(discordUser.Id);
    if (user == null)
    {
        await ctx.CreateResponseAsync(new DiscordInteractionResponseBuilder()
            .AddEmbed(new DiscordEmbedBuilder().CreateErrorEmbed("You can't grant all cosmetics to a user that isn't registered!"))
            .AsEphemeral());
        return;
    }

    _internalService.GrantAllCosmetics(user.Id);

    // EXCEPTION IS THROWN HERE
    await ctx.CreateResponseAsync(new DiscordInteractionResponseBuilder()
        .AddEmbed(new DiscordEmbedBuilder().CreateSuccessEmbed($"Congrats! **{discordUser.Username}** has been granted all cosmetics"))
        .AsEphemeral());
}
```

# Steps to reproduce
Happens randomly, not sure how to reproduce

# Notes
I assumed this may be a client sided issue, so I attempted restarting Discord to re-authenticate etc, but this didn't make a difference.

**Comment by OoLunar** [comment]
Do you have any events that respond to interactions?

**Comment by cyclonefreeze** [comment]
Hi,

I use the ComponentInteractionCreated event,

```
client.ComponentInteractionCreated += (_, e) =>
{
    if (e.Id.Contains("Commands"))
    {
        var title = "";
        var description = "";

        switch (e.Id)
        {
            case "authCommands":
                title = "🔑 Authentication";
                description = Globals.AUTH_COMMANDS;
                break;
            case "matchmakerCommands":
                title = "🏁 Matchmaker";
                description = Globals.MATCHMAKER_COMMANDS;
                break;
            case "statusCommands":
                title = "🌐 Status";
                description = Globals.STATUS_COMMANDS;
                break;
            case "userCommands":
                title = "👥 User";
                description = Globals.USER_COMMANDS;
                break;
        }
        
        e.Interaction.CreateResponseAsync(InteractionResponseType.UpdateMessage, new DiscordInteractionResponseBuilder()
            .AddEmbed(new DiscordEmbedBuilder()
                .WithTitle(title)
                .WithDescription(description)
                .WithColor(new DiscordColor("#7F9DD2")))
            .AddComponents(
                new DiscordButtonComponent(e.Id == "authCommands" ? ButtonStyle.Primary : ButtonStyle.Secondary, "authCommands", "🔑 Authentication"),
                new DiscordButtonComponent(e.Id == "matchmakerCommands" ? ButtonStyle.Primary : ButtonStyle.Secondary, "matchmakerCommands", "🏁 Matchmaker"),
                new DiscordButtonComponent(e.Id == "statusCommands" ? ButtonStyle.Primary : ButtonStyle.Secondary, "statusCommands", "🌐 Status"),
                new DiscordButtonComponent(e.Id == "userCommands" ? ButtonStyle.Primary : ButtonStyle.Secondary, "userCommands", "👥 User"))
            .AsEphemeral()
        );
    }
    else
    {
        var instance = Matchmaker.Instance;
    
        switch (e.Id)
        {
            case "pageStart":
                instance.CurrentPage = 0;
                break;
            case "pageLeft":
                instance.CurrentPage--;
                break;
            case "pageRight":
                instance.CurrentPage++;
                break;
            case "pageEnd":
                instance.CurrentPage = instance.Pages.Count - 1;
                break;
        }
        
        var page = instance.Pages[instance.CurrentPage].Content;

        var shouldDisableLeft = instance.CurrentPage <= 0;
        var shouldDisableRight = instance.CurrentPage >= instance.Pages.Count - 1;
        
        e.Interaction.CreateResponseAsync(InteractionResponseType.UpdateMessage, new DiscordInteractionResponseBuilder()
            .AddEmbed(new DiscordEmbedBuilder()
                .WithTitle("Queued players")
                .WithDescription(page.Replace($"Page {instance.CurrentPage + 1}:\n", ""))
                .WithColor(new DiscordColor("#7F9DD2"))
                .WithFooter($"Page {instance.CurrentPage + 1}/{instance.Pages.Count}"))
            .AddComponents(
                new DiscordButtonComponent(ButtonStyle.Secondary, "pageStart", null, shouldDisableLeft, new DiscordComponentEmoji(DiscordEmoji.FromUnicode("⏪"))),
                new DiscordButtonComponent(ButtonStyle.Secondary, "pageLeft", null, shouldDisableLeft, new DiscordComponentEmoji(DiscordEmoji.FromUnicode("⬅️"))),
                new DiscordButtonComponent(ButtonStyle.Secondary, "pageRight", null, shouldDisableRight, new DiscordComponentEmoji(DiscordEmoji.FromUnicode("➡️"))),
                new DiscordButtonComponent(ButtonStyle.Secondary, "pageEnd", null, shouldDisableRight, new DiscordComponentEmoji(DiscordEmoji.FromUnicode("⏩"))))
            .AsEphemeral()
        );
    }

    return Task.CompletedTask;
};
```

**Comment by OoLunar** [comment]
While I am closing this as stale, I still think this is caused by not responding fast enough. Though there seems to be nothing particularly wrong or time-consuming in your code, it could also be caused by a poor internet connection.
