### ISSUE TITLE
Cannot use vpn

### ISSUE THREAD

**Issue by HeroinGyrl** [DSharpPlus/DSharpPlus#1287]
when I use a vpn I get this exception:

```
[2022-04-18 22:01:49 +02:00] [104 /EventHandler] [Crit ] Exception event handler System.Threading.Tasks.Task <<Main>$>g__Discord_ClientErrored|0_2(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.ClientErrorEventArgs) (defined in Program) threw an exception
Newtonsoft.Json.JsonSerializationException: Error getting value from 'ScopeId' on 'System.Net.IPAddress'.
 ---> System.Net.Sockets.SocketException (10045): The operation is not supported by the object type referred to.
   at System.Net.IPAddress.get_ScopeId()
   at lambda_method851(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
```

**Comment by OoLunar** [comment]
You'll need to send your code in order for us to help you. Don't worry, I'm able to use my VPN just fine, so it's probably a code issue
