### ISSUE TITLE
NullReferenceException in VoiceServerUpdated

### ISSUE THREAD

**Issue by Foxite** [DSharpPlus/DSharpPlus#1338]
My music bot randomly logs this error:

```
[104 /EventHandler] [Error] Event handler exception for event VOICE_SERVER_UPDATED thrown from System.Threading.Tasks.Task Client_VoiceServerUpdate(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.VoiceServerUpdateEventArgs) (defined in DSharpPlus.VoiceNext.VoiceNextExtension)
System.NullReferenceException: Object reference not set to an instance of an object.
  at DSharpPlus.VoiceNext.VoiceNextExtension.Client_VoiceServerUpdate(DiscordClient client, VoiceServerUpdateEventArgs e)
  at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)
```

I have no custom event handlers for VoiceServerUpdated.

Not sure if it's actually causing any problems but it might be, given that I'm still experiencing #1294 and I'm starting to run out of explanations.

I've tried to figure out where in Client_VoiceServerUpdate this error originates, but I failed. I've configured my build process to include pdb files from DSharpPlus which gives me line numbers in the stack traces. If/when I see this happening again I'll get back here with the line numbers.

**Comment by akiraveliara** [comment]
closing as VNext has been removed
