### ISSUE TITLE
Slash commands error an InedxOutOfRangeException after longer runtime

### ISSUE THREAD

**Issue by BlackLotusLV** [DSharpPlus/DSharpPlus#1350]
# Summary
After a longer runtime commands stop responding, and console outputs an error. Happens on both 

# Details
Initial startup, everything works as intended no issues, at a random time after the bot has been running, can be within a day, can be multiple days, an interaction would fail not executing the code and simply erroring in the console.

Individual commands get affected. If one command/command group can't be executed another might be fine.

This affects both global and server specific slash commands.

```
[2022-07-20 13:41:48 +00:00] [204 /SlashErrored] [Error] DekoSeishin tried executing 'mod' but it errored
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass47_0.<<InteractionHandler>b__0>d.MoveNext()
```

# Steps to reproduce
-

# Notes
Current fix is simply restarting the bot, which is a bad solution and should not be relied upon.

**Comment by VelvetThePanda** [comment]
It's been ~4 months since this issue was opened. Is this still occurring?

**Comment by OoLunar** [comment]
I'm unable to reproduce and with the current stack trace I'm unable to thoroughly debug. Closing as stale
