### ISSUE TITLE
NullReferenceException occurs on start up

### ISSUE THREAD

**Issue by JackSteel97** [DSharpPlus/DSharpPlus#1459]
# Summary
A `NullReferenceException` occurs on start up of a bot using `4.4.0.nightly-01260`

# Details

> [21:07:21 ERR] Socket handler suppressed an exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.OnReadyEventAsync(ReadyPayload ready, JArray rawGuilds, JArray rawDmChannels)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|484_1(IWebSocketClient sender, SocketMessageEventArgs e)

# Steps to reproduce
1. Install `4.4.0.nightly-01260`
2. Start the bot

# Notes
Does not occur in `4.4.0.nightly-01258`

**Comment by OoLunar** [comment]
Unable to reproduce on `4.4.0-nightly-01358`, assuming the bug has been fixed since.
