### ISSUE TITLE
DiscordMember.SendMessageAsync throws InvalidCastException

### ISSUE THREAD

**Issue by oliverbooth** [DSharpPlus/DSharpPlus#1512]
# Summary
`InvalidCastException` is thrown when calling `DiscordMember.SendMessageAsync`, due to what I am told is a change in how group DMs are handled in the API. 

# Details
While I work and build a bot, `InvalidCast` from DSharpPlus,
Expecting this, I was not. The stack trace that it gave is thus:
```
Event handler exception for event MESSAGE_CREATED thrown from System.Threading.Tasks.Task <<Main>$>g__OnMessageCreated|0_0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.MessageCreateEventArgs) (defined in Program): System.InvalidCastException: Unable to cast object of type 'DSharpPlus.Enti
ties.DiscordChannel' to type 'DSharpPlus.Entities.DiscordDmChannel'.
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at DSharpPlus.Net.DiscordApiClient.CreateDmAsync(UInt64 recipient_id)
   at DSharpPlus.Entities.DiscordMember.SendMessageAsync(String content)
```

To reproduce this error true, simply send a message back.
Take this code I give to you, the bot will give a log to track:
```cs
var client = new DiscordClient(new DiscordConfiguration
{
    Token = Environment.GetEnvironmentVariable("TOKEN"),
    Intents = DiscordIntents.AllUnprivileged | DiscordIntents.MessageContents
});
client.MessageCreated += OnMessageCreated;

await client.ConnectAsync();
await Task.Delay(-1);

async Task OnMessageCreated(DiscordClient sender, MessageCreateEventArgs args)
{
    if (args.Guild is not { } guild) return;

    var member = await guild.GetMemberAsync(args.Author.Id);
    if (args.Message.Content == "dm me")
        await member.SendMessageAsync("Hello World");
}
```

# Steps to reproduce
1. Call `SendMessageAsync` on any `DiscordMember`
2. That's all folks

# Notes
n/a

**Comment by VelvetThePanda** [comment]
Caused by an issue in #1455 regarding the added converter. b18e6e0c should fix it
