### ISSUE TITLE
Unsafe Dispose methods and incorrect implementation of the Dispose pattern causes NRE when objects are garbage collected

### ISSUE THREAD

**Issue by Kaoticz** [DSharpPlus/DSharpPlus#1547]
I'm writing an actual bug report to make sure the issue doesn't get buried in DAPI.

# Summary
These are actually two separate issues.

## The Dispose in some classes is not safe
According to the [official Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose), the Dispose method should written in a way that does not cause exceptions to be thrown.
```
To help ensure that resources are always cleaned up appropriately, a Dispose method should be idempotent, such that it is callable multiple times without throwing an exception. Furthermore, subsequent invocations of Dispose should do nothing.
```
Several classes in DSharpPlus however, contain Dispose methods that would throw an exception when executed more than once. They usually follow the pattern below, where a method is called from a class member, then set to `null`:
```cs
public void Dispose()
{
    _someField.SomeMethodCall();
    _someField = null;
}
```
This Dispose method is not safe because the class member is being set to `null`, so the second time the method is executed, it throws a NullReferenceException (NRE).

The obvious way to fix it would be adding a null guard before the method call.
```cs
_someField?.SomeMethodCall();
```
Now, this wouldn't normally be an issue if said classes are not public and their Dispose methods are not being called more than once. However, due to the second issue I'm describing next, this mistake ends up having catastrophic effects on the running application.

## Incorrect implementation of the Dispose pattern

According to the same [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose):
```
The .NET garbage collector does not allocate or release unmanaged memory. The pattern for disposing an object, referred to as the dispose pattern, imposes order on the lifetime of an object. The dispose pattern is used for objects that implement the IDisposable interface. This pattern is common when interacting with file and pipe handles, registry handles, wait handles, or pointers to blocks of unmanaged memory, because the garbage collector is unable to reclaim unmanaged objects.
```
When using Visual Studio's or Omnisharp's intellisense, you have the option of implementing the Dispose pattern for any object that implements `IDisposable`, which generates the following code (with comments):
```cs
private bool _disposedValue;

protected virtual void Dispose(bool disposing)
{
    if (!_disposedValue)
    {
        if (disposing)
        {
            // TODO: dispose managed state (managed objects)
        }

        // TODO: free unmanaged resources (unmanaged objects) and override finalizer
        // TODO: set large fields to null
        _disposedValue = true;
    }
}

// // TODO: override finalizer only if 'Dispose(bool disposing)' has code to free unmanaged resources
// ~TestClass()
// {
//     // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
//     Dispose(disposing: false);
// }

public void Dispose()
{
    // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
    Dispose(disposing: true);
    GC.SuppressFinalize(this);
}
```
There are a few takeaways you can take from this code:
- If your class does not have unmanaged resources, it **should not** declare a finalizer.
- In case you do declare a finalizer, **only** unmanaged resources should be disposed by it.
- The public facing Dispose method should dispose **both** managed and unmanaged resources, and **also** suppress the execution of the finalizer.

Now when you look at DSharpPlus classes, you find this:
```cs
~ClassName()
{
    this.Dispose();
}
```
Take into account the previous issue of Dispose methods not being safe and you'll realize that objects that have been disposed by the library will cause a NRE when they are collected by the garbage collector, causing an instant crash on the entire application.
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DSharpPlus.Interactivity
  StackTrace:
   at DSharpPlus.Interactivity.EventHandling.ReactionCollector.Dispose()
   at DSharpPlus.Interactivity.InteractivityExtension.Dispose()
   at DSharpPlus.Interactivity.InteractivityExtension.Finalize()
```
The exception above occurred [here](https://github.com/DSharpPlus/DSharpPlus/blob/14e54aeaa2d0ec66aab284528cf9205a9302dabb/DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs#L171-L197), but this same pattern is scattered throughout the entire code base, so this could've occurred anywhere else. Therefore, they also need to be fixed.

# Steps to reproduce
1. Create one of such objects that incorrectly implements this pattern.
2. Call `Dispose()` twice.
3. Exception is thrown.
OR
1. Create one of such objects that incorrectly implements this pattern.
2. Call `Dispose()` once.
3. Force a garbage collection.
4. Exception is thrown.

# Possible solutions
For the first issue, null guards should be added to ensure the Dispose method does not throw exceptions when executed more than once.

As for the second issue:

## The obvious solution:
Just remove the finalizer. These classes often don't use any unmanaged resource, so there is no reason to have a finalizer in the first place.

## Alternative solution:
Add `GC.SupressFinalizer(this);` to the `Dispose()` methods, so the finalizer does not get called for objects that have been disposed.

# Notes
DSharpPlus 4.4.0
.NET 7.0.202

For an excruciatingly boring and extremely theoretical explanation of the Dispose method and finalizers, check out [this blog post](https://joeduffyblog.com/2005/04/08/dg-update-dispose-finalization-and-resource-management/).

**Comment by akiraveliara** [comment]
Thank you for the report! i'll look into it shortly, from first glance, we'll consider removing the finalizers
