### ISSUE TITLE
DiscordMember.TimeoutAsync() non ASCII reason

### ISSUE THREAD

**Issue by bakirov-eldar** [DSharpPlus/DSharpPlus#1657]
I can't use non ascii characters in reason parameter in the latest nightly builds.

```
System.Net.Http.HttpRequestException: Request headers must contain only ASCII characters.
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async)
   at System.Net.Http.HttpConnection.WriteStringAsync(String s, Boolean async, Encoding encoding)
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer, Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DSharpPlus.Net.RestClient.<>c__DisplayClass22_0`1.<<ExecuteRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.Net.RateLimitPolicy.ImplementationAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at DSharpPlus.Net.RestClient.ExecuteRequestAsync[TRequest](TRequest request)

```

**Comment by OoLunar** [comment]
Audit logs use the `X-Audit-Log-Reason` http header to send Discord the reason behind the auditable action. Per the HTTP spec, only ASCII characters can be sent within the HTTP headers. You'll find this behavior to be consistent across all auditable methods.

Unfortunately this means that audit log reasons can only be in ASCII characters, which is English only. I understand how this can be quite limiting.

However I do not see a solution immediately available. Previously, Discord allowed us to append the `?reason` query to the url. Now that query is deprecated an no longer used within the lib.

Other contributors are welcome to comment, but once more, I do not see an immediate solution. I apologize for the bad news.

**Comment by bakirov-eldar** [comment]
> Audit logs use the `X-Audit-Log-Reason` http header to send Discord the reason behind the auditable action. Per the HTTP spec, only ASCII characters can be sent within the HTTP headers. You'll find this behavior to be consistent across all auditable methods.
> 
> Unfortunately this means that audit log reasons can only be in ASCII characters, which is English only. I understand how this can be quite limiting.
> 
> However I do not see a solution immediately available. Previously, Discord allowed us to append the `?reason` query to the url. Now that query is deprecated an no longer used within the lib.
> 
> Other contributors are welcome to comment, but once more, I do not see an immediate solution. I apologize for the bad news.

Uri.EscapeDataString(reason)

Url encode is enough

**Comment by OoLunar** [comment]
I'll... Test it. However I have zero faith that Discord will render this correctly.

**Comment by bakirov-eldar** [comment]
> Я... проверю это. Однако я не верю, что Discord отобразит это правильно.

![image](https://github.com/DSharpPlus/DSharpPlus/assets/82159025/bca7110e-7f38-44eb-a076-9c630e1ea433)

**Comment by Lulalaby** [comment]
> I'll... Test it. However I have zero faith that Discord will render this correctly.

Uri.EscapeDataString does work for this.
Discord is handling encoded headers correctly.
