### ISSUE TITLE
Lavalink connection

### ISSUE THREAD

**Issue by Marieldril** [DSharpPlus/DSharpPlus#1786]
### Summary

Bot: 
`Failed to connect to Lavalink, retrying in 7500 ms.
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '200' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.Lavalink.LavalinkNodeConnection.StartAsync()`
   
Lavalink: 
`lavalink.server.config.WebsocketConfig   : This is the old Lavalink websocket endpoint. Please use /v4/websocket instead. If you are using a client library, please update it to a Lavalink v4 compatible version or use Lavalink v3 instead.` 

I downloaded newest Lavalink version from here: https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.3
  
And ran code copied from docs: https://dsharpplus.github.io/DSharpPlus/articles/audio/lavalink/setup.html

In previous version it was working.
 

### What version of the library are you using?

v4.4.6 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Operating System

Windows, Linux

### Reproduction Steps

Download Lavalink: https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.3
Run code from docs: https://dsharpplus.github.io/DSharpPlus/articles/audio/lavalink/setup.html

### Exceptions or other error messages

```txt
Bot: 
`Failed to connect to Lavalink, retrying in 7500 ms.
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '200' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.Lavalink.LavalinkNodeConnection.StartAsync()`
   
Lavalink: 
`lavalink.server.config.WebsocketConfig   : This is the old Lavalink websocket endpoint. Please use /v4/websocket instead. If you are using a client library, please update it to a Lavalink v4 compatible version or use Lavalink v3 instead.`
```

**Comment by Plerx2493** [comment]
We dont support DSP.Lavalink anymore, use [Lavalink4Net ](https://github.com/angelobreuer/Lavalink4NET) instead or use an older version of Lavalink

**Comment by akiraveliara** [comment]
we don't support latest lavalink.
