### ISSUE TITLE
Nullable Enum cannot be used as SlashCommand argument

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#1865]
### Summary

Whether adding a ChoiceProvider or not, a nullable Enum cannot be used as a SlashCommand argument without `System.InvalidOperationException: No type mapping found for parameter type 'Nullable`1'` in `GUILD_DOWNLOAD_COMPLETED`

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Ubuntu 22.04

### Reproduction Steps

By removing the final argument `region`, this error goes away.
By changing the final argument `region` to non-nullable, this error goes away.

```c#
[Command("update-gp")]
[Description("Change the details of your G-Portal gameserver-only the specified options are updated")]
[RequirePermissions(botPermissions: DiscordPermissions.None, userPermissions: DiscordPermissions.ManageGuild)]
public async Task UpdateGPAsync
(
SlashCommandContext ctx,

[SlashAutoCompleteProvider<GameserverAutocompleteHandler>]
[Parameter("gameserver")]
[Description("Choose the gameserver to modify")]
int gameserverId,

[Parameter("nickname")]
[Description("Change the nickname of your G-Portal gameserver")]
string? newName = null,

[Parameter("gportal-gameserver-id")]
[Description("Change the ID of your G-Portal gameserver")]
int? gportalGameserverId = null,

[Parameter("region")]
[Description("Change the region of your G-Portal gameserver")]
Region? region = null
)

```

### Trace Logs

```log
18:20:48 ERR] Event handler exception for event GUILD_DOWNLOAD_COMPLETED thrown from System.Threading.Tasks.Task <ConfigureAsync>b__0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.GuildDownloadCompletedEventArgs) (defined in DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor+<>c__DisplayClass11_0)
System.InvalidOperationException: No type mapping found for parameter type 'Nullable`1'
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationParameterAsync(Command command, CommandParameter parameter, Nullable`1 i)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationParameterAsync(Command command)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationCommandAsync(Command command)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.RegisterSlashCommandsAsync(CommandsExtension extension)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.<>c__DisplayClass11_0.<<ConfigureAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
[18:20:48 ERR] No type mapping found for parameter type 'Nullable`1'
System.InvalidOperationException: No type mapping found for parameter type 'Nullable`1'
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationParameterAsync(Command command, CommandParameter parameter, Nullable`1 i)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationParameterAsync(Command command)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.ToApplicationCommandAsync(Command command)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.RegisterSlashCommandsAsync(CommandsExtension extension)
   at DSharpPlus.Commands.Processors.SlashCommands.SlashCommandProcessor.<>c__DisplayClass11_0.<<ConfigureAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at DSharpPlus.AsyncEvents.AsyncEvent`2.<>c__DisplayClass7_0.<<InvokeAsync>b__0>d.MoveNext()
```

**Comment by ecrocombe** [comment]
DSP.Commands lib
