### ISSUE TITLE
Reconnect and resume are not working as expected

### ISSUE THREAD

**Issue by 9True** [DSharpPlus/DSharpPlus#1955]
### Summary

Any attempt at resuming a bot or answering a reconnection request from Discord will fail. On the first attempt, the websocket crashes and D#+ recreate a new connection instead (1718205339239.log). The bot is still usable, but if there was any event between the disconnection and the reconnection, they won't be recovered (as it doesn't resume but creates a new session)

On any subsequent attempt though, it still errors out, but there's a duplication bug where D#+ is attempting to reconnect twice (and will throw a "4005 Already authenticated" error) (1718207258245.log). 

[1718205339239.log](https://github.com/user-attachments/files/15807738/1718205339239.log)
[1718207258245.log](https://github.com/user-attachments/files/15807737/1718207258245.log)

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

W10

### Reproduction Steps

Run the bot and wait for Discord to ask for a reconnect ; or trigger a manually reconnect one way or another

### Trace Logs

```log
[1718205339239.log](https://github.com/user-attachments/files/15807738/1718205339239.log)
[1718207258245.log](https://github.com/user-attachments/files/15807737/1718207258245.log)
```

### Exceptions or other error messages

```txt
11:29:08 [ERR] An error occurred in the DSharpPlus gateway. 
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at DSharpPlus.Net.WebSocket.WebSocketClient.ReceiverLoopAsync()
```

**Comment by Plerx2493** [comment]
I think this issue was resolve in #1962
