### ISSUE TITLE
Interactivity trying to de-register events, causing exception on disposing the DIscordClient.

### ISSUE THREAD

**Issue by ecrocombe** [DSharpPlus/DSharpPlus#2004]
### Summary

Using interactivity extension, on disposing of the DiscordClient, the lib is still trying to de-register events.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Alpine/Docker

### Reproduction Steps

Use Interactivity on 5.0.0-nightly-02313. 
`DiscordClient.DisconnectAsync()` after a successful startup.

### Exceptions or other error messages

```txt
Unhandled exception. System.NotSupportedException: Specified method is not supported.
   at DSharpPlus.DiscordClient.remove_ComponentInteractionCreated(AsyncEventHandler`2 value)
   at DSharpPlus.Interactivity.EventHandling.ComponentEventWaiter.Dispose()
   at DSharpPlus.Interactivity.InteractivityExtension.Dispose()
   at DSharpPlus.DiscordClient.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
```

**Comment by akiraveliara** [comment]
known issue, will be fixed in the near future

**Comment by ecrocombe** [comment]
Closing, record of this issue is kept elsewhere.
