### ISSUE TITLE
Slash Command times out and errors when used in a server the bot is not a member of

### ISSUE THREAD

**Issue by HazzyJC** [DSharpPlus/DSharpPlus#2072]
### Summary

The command works in DM's and servers the bot IS in, but not servers the bot ISNT in. I ignored this issue for a while because discord didn't allow use of a self app in servers with >15 members, but that seemingly has changed recently as I've noticed my other self apps able to be used in servers they arent in. The bot will time out and send the message "The application did not respond", and it will return an error in the console that I'll attach below.

### What version of the library are you using?

v4.4.9 (Stable)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 6.0

### Operating System

Windows/Linux

### Reproduction Steps

Create a command with DSharpPlus, Edit the command with a patch with this request:
  {
    "integration_types": [0,1],
    "contexts": [0,1,2]
  }

- Setup the command with the interaction response type DeferredChannelMessageWithSource
- Add the app to your discord account
- Run the command in a server the bot isnt a member of

### Exceptions or other error messages

```txt
System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.UpdateUser(DiscordUser usr, Nullable`1 guildId, DiscordGuild guild, TransportMember mbr)
   at DSharpPlus.DiscordClient.OnInteractionCreateAsync(Nullable`1 guildId, UInt64 channelId, TransportUser user, TransportMember member, DiscordInteraction interaction)
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|484_1(IWebSocketClient sender, SocketMessageEventArgs e)
```

**Comment by Plerx2493** [comment]
This bug is very likely fixed in the nightly branch.
