### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000

### ISSUE THREAD

**Issue by wthks** [DSharpPlus/DSharpPlus#2074]
### Summary

```
fail: DSharpPlus.DiscordClient[0]
      Dispatch threw an exception:
      System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')
         at DSharpPlus.Entities.DiscordMember..ctor(TransportMember member)
         at DSharpPlus.DiscordClient.UpdateCachedGuild(DiscordGuild newGuild, JArray rawMembers)
         at DSharpPlus.DiscordClient.OnGuildCreateEventAsync(DiscordGuild guild, JArray rawMembers, IEnumerable`1 presences)
         at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
         at DSharpPlus.DiscordClient.ReceiveGatewayEventsAsync()
```

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 9.0 Previews

### Operating System

windows

### Reproduction Steps

Occured after update.

**Comment by OoLunar** [comment]
Does this occur on .NET 8?

**Comment by Plerx2493** [comment]
> .NET 9.0 Previews

**Comment by akiraveliara** [comment]
we're gonna need more information. system info, runtime info, locale/calendar settings, architecture, anything.
