### ISSUE TITLE
Message.Channel is sometimes null in events when ChannelId is not

### ISSUE THREAD

**Issue by Erisa** [DSharpPlus/DSharpPlus#2076]
### Summary

https://discord.com/channels/379378609942560770/1094835363475886163/1274915537998188576
Sometimes in an event you'll get this:

![image](https://github.com/user-attachments/assets/62af0d25-7103-467f-bbd7-2c3aa0f1ebde)

where the Message doesn't have a Channel but the ChannelId is clearly there. This probably happens because the channel isn't cached and fails to be cached for whatever reason.

May be similar to https://github.com/DSharpPlus/DSharpPlus/issues/2051 which is a similar cache not caching issue.

### What version of the library are you using?

v5.0.0-nightly (make sure you are using the latest nightly!)

### What .NET version are you using? Make sure to use the latest patch release for your major version.

.NET 8.0

### Operating System

Windows 11

### Reproduction Steps

* Create a ReactionAdd event that logs or uses something in `e.Message.Channel` where `e` is the event args
* Startup the bot
* Before any messages or other events, immediately react to a message
* Check the Message.Channel for that event

### Trace Logs

```log
[2024-08-19 03:47:53 +01:00] [Verbose] Length for the last inbound gateway event: 1877
[2024-08-19 03:47:53 +01:00] [Verbose] Payload for the last inbound gateway event:
"{\"t\":\"MESSAGE_REACTION_ADD\",\"s\":11,\"op\":0,\"d\":{\"user_id\":\"228574821590499329\",\"type\":0,\"message_id\":\"1274770079032283157\",\"message_author_id\":\"469643838974066729\",\"member\":{\"user\":{\"username\":\"erisachu\",\"public_flags\":4326144,\"id\":\"228574821590499329\",\"global_name\":\"Erisa\",\"display_name\":\"Erisa\",\"discriminator\":\"0\",\"clan\":null,\"bot\":false,\"avatar_decoration_data\":null,\"avatar\":\"ed550f6da4c4552f6a92840134478e44\"},\"roles\":[\"1247615643197374596\",\"1225233039215296542\",\"1082368846842830878\",\"885928970162417704\",\"885928970162417705\",\"885928970162417706\",\"885928970162417707\",\"885928970162417708\",\"885928970162417709\",\"885928970162417710\",\"885928970162417711\",\"885928970162417712\",\"885928970162417713\",\"910691209511587890\",\"946443325609762858\",\"885928970183393340\",\"1196155537390321725\",\"885928970183393342\",\"885928970137260094\",\"885928970183393341\",\"885928970149851196\",\"885928970149851197\",\"885928970149851198\",\"885928970149851199\",\"885928970137260096\",\"885928970137260097\",\"885928970137260098\",\"885928970137260099\",\"885928970137260100\",\"885928970137260101\",\"885928970137260102\",\"885928970149851200\",\"885928970149851201\",\"885928970149851202\",\"885928970137260095\",\"885928970183393345\",\"885928970183393343\",\"885928970149851203\",\"885928970183393346\",\"896574224557285417\",\"885928970183393347\",\"885928970149851204\",\"885928970170802266\",\"885928970170802267\",\"885928970149851205\",\"885928970170802269\",\"885928970170802270\",\"885928970170802271\",\"885928970170802272\",\"885928970170802273\",\"885928970170802274\",\"885928970170802275\",\"885928970183393344\"],\"premium_since\":null,\"pending\":false,\"nick\":null,\"mute\":false,\"joined_at\":\"2021-09-10T16:45:26.260000+00:00\",\"flags\":0,\"deaf\":false,\"communication_disabled_until\":null,\"banner\":null,\"avatar\":null},\"emoji\":{\"name\":\"Heartosoft\",\"id\":\"413429915187281940\"},\"channel_id\":\"885928971068387352\",\"burst\":false,\"guild_id\":\"885928970137260093\"}}"
```

### Exceptions or other error messages

```txt
[2024-08-19 02:13:10 +00:00] [Error] Event handler exception for event "DSharpPlus.EventArgs.MessageReactionAddedEventArgs" thrown from "System.Threading.Tasks.Task <CanonicalizeSimpleDelegateHandler>b__0(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.DiscordEventArgs, System.IServiceProvider)" (defined in "DSharpPlus.EventHandlerCollection+<>c__DisplayClass8_0").
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cliptok.Events.ReactionEvent.OnReaction(DiscordClient _, MessageReactionAddedEventArgs e) in /app/Events/ReactionEvent.cs:line 9
   at DSharpPlus.Clients.DefaultEventDispatcher.<>c__DisplayClass5_0`1.<<DispatchAsync>b__0>d.MoveNext()
```

**Comment by Erisa** [comment]
From further testing this (and #2060) seems to have been introduced in https://github.com/DSharpPlus/DSharpPlus/commit/1d54d42c55c6c3719928c5f3f153adf8c1b92da8
