### ISSUE TITLE
Race condition in DiscordApiClient.PrepareMessage

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#219]
# Summary
A race condition when loading message history when a guild's members are still loading causes (if I'm correct, which I rarely am) the Members collection to be modified while it's being accessed here:
https://github.com/NaamloosDT/DSharpPlus/blob/a6e23d8d28b301905d1e2d46f608c7b40b12cf02/DSharpPlus/Net/DiscordApiClient.cs#L63-L67
This throws an InvalidOperationException that bubbles up to the callee.

# Details
Ask WamWooWham!#5274 i guess

```
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelMessagesAsync>d__43.MoveNext()
```

# Steps to reproduce
1. I'll get to it in a bit

**Comment by uwx** [comment]
This is likely still an issue, as `DiscordGuild._members` is not thread-safe.

Candidates for causing the exception are writes at

https://github.com/DSharpPlus/DSharpPlus/blob/8d1fdc499c4c7774b27f940a476995fb2b2e3859/DSharpPlus/DiscordClient.cs#L903 OnReadyEventAsync, unlikely and since it would imply accessing guilds before `Ready`, which is obviously not a supported scenario.

https://github.com/DSharpPlus/DSharpPlus/blob/9a81c4647cfa755c4ce80c6ace362ca274e2d645/DSharpPlus/Entities/DiscordGuild.cs#L570 DiscordGuild.GetMemberAsync when the member is not in cache and it is thus updated, a very rare scenario

https://github.com/DSharpPlus/DSharpPlus/blob/8d1fdc499c4c7774b27f940a476995fb2b2e3859/DSharpPlus/DiscordClient.cs#L1367 OnGuildMemberAddEventAsync, also very rare

https://github.com/DSharpPlus/DSharpPlus/blob/8d1fdc499c4c7774b27f940a476995fb2b2e3859/DSharpPlus/DiscordClient.cs#L1834 OnGuildMembersChunkEventAsync, this is likely what causes the exception along with the following one

https://github.com/DSharpPlus/DSharpPlus/blob/8d1fdc499c4c7774b27f940a476995fb2b2e3859/DSharpPlus/DiscordClient.cs#L2253 UpdateCachedGuild is my second candidate for it

A fix for this issue would be to lock on _member but that's quite slow. We can use a [ReaderWriterLockSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.readerwriterlockslim?redirectedfrom=MSDN&view=netframework-4.7.2) which would be ever so slightly faster when doing a lot of reads, but that still doesn't feel optimal. We could use [a custom concurrent HashSet implementation](https://github.com/i3arnon/ConcurrentHashSet) as the BCL has none, but I'm not sure how wary any of you guys are about introducing general-purpose types like that. We'd also need to write a custom serializer for it, but that wouldn't be too much work.

I'm not sure where to follow from this point, so I'm going to wait for you guys' opinions.
