### ISSUE TITLE
Null ref exceptions threw by websocket

### ISSUE THREAD

**Issue by Kiritsu** [DSharpPlus/DSharpPlus#298]
# Summary
When you try to connect with a DiscordShardedClient, when the shards are starting up, it sometimes throw this NullReferenceException: 
```cs
[11/06/2018 20:32:58] [Websocket] [Error] Socket swallowed an exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.DiscordClient.<HandleSocketMessageAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DSharpPlus.DiscordClient.<<InternalConnectAsync>g__SocketOnMessage|53_1>d.MoveNext() This is bad!!!!
```
It happens completely randomly.

I noticed this `Exception` when I was trying to start my test bot (in 4 guilds) with `ShardCount` sets to `10` (I was testing the Sharding with a manual ShardCount on my test bot before trying on my "main" bot that has like 1k guilds). The shards load successfully, but are sometimes seems to be throwing an exception.

# Details
- .NET Core 2.0
- Windows 10 Enterprise LTSB 2016
- DSharpPlus version: 4.0.0-beta-00460
- Visual Studio 2017

# Steps to reproduce
Try to start a bot that has a very few guilds and set the ShardCount to a number that is more than your guilds count. It *should* be reproducing the "bug".
^ edit: seems to be happening no matter how many shards are set

**Comment by Kriste00** [comment]
I have this problem too but my shardCount is 10 and guildCount 7100, so i dont think the shardCount have to be hightr than the guildCount.

**Comment by Emzi0767** [comment]
Well the sharded client will be scraped anyways, in favour of a new, better one. As for how why this happens, no idea, would need to debug some other day.

**Comment by uwx** [comment]
Seems like `payload.Data` during HELLO is expected to be a JObject but is not one, for some reason. That's the only place I could find where there could possibly be a NRE, although this issue is nearly a year old so the stack trace might not even be valid anymore.

**Comment by Neuheit** [comment]
Closing due to inactivity. This stack trace is outdated and the exception itself was likely fixed from the rework to the `WebSocketClient`.
