### ISSUE TITLE
Exception thrown when getting pinned messages in a channel

### ISSUE THREAD

**Issue by uwx** [DSharpPlus/DSharpPlus#411]
# Summary
A JsonReaderException is thrown rarely when getting a channel's pinned messages.

# Details
The stack trace is condensed due to inlining.
```
Newtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1.
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   at DSharpPlus.Net.DiscordApiClient.GetPinnedMessagesAsync(UInt64 channel_id) in /tmp/build_ba6cbb7bd319d325ffc7455b3224bf81/DSharpPlus/DSharpPlus/Net/DiscordApiClient.cs:line 800
   at RayBotSharp.Persistence.Saving.SaveData() in /tmp/build_ba6cbb7bd319d325ffc7455b3224bf81/RayBotSharp/Persistence/Saving.cs:line 58
```

# Steps to reproduce
None yet, but this is the code that was used:
```cs
var chan = guild.GetChannel(Constants.Channels.RayBot2SavingLoading);
var msg = await chan.SendFileAsync(stream, $"hello! saved at {DateTime.UtcNow}");
var pins = await chan.GetPinnedMessagesAsync();
```

# Notes
I will look into this later today.

**Comment by Neuheit** [comment]
Closing this issue because I could not reproduce and due to inactivity. Feel free to reopen if you are still experiencing this.
