### ISSUE TITLE
`System.MemberAccessException` on initial startup with .NET Core 3.0 Preview builds

### ISSUE THREAD

**Issue by Gnbrkm41** [DSharpPlus/DSharpPlus#431]
# Summary
After the `DiscordClient.ConnectAsync()` is called it appears that some part in `WebSocket` throws an exception. `System.MemberAccessException: Type initializer was not callable.` is thrown and every single message received leaves a warning `[Event] [Warning] Could not find channel last message belonged to.`. Essentially all things just break apart, like not being able to `GetChannel()` and whatnot...

# Details

## Environment
* Raspberry Pi 3B+ with Raspbian. It was a relatively fresh install (just finished updating and installed docker). Happened when I tried:
  * Docker .NET Core 3.0 preview image (`mcr.microsoft.com/dotnet/core/runtime:3.0`), with framework dependent deployment builds
  * Ran directly in Raspbian, self-deployed build
* Cannot be reproduced on Windows 10 w/ .NET Core 3.0 P5

## Console output
```
root@90baf8ca8bbf:/app# dotnet ./AyyLmao.dll
[2019-06-05 22:03:19 +00:00] [DSharpPlus] [Info] DSharpPlus, version 4.0.0-nightly-00600
[2019-06-05 22:03:20 +00:00] [REST] [Debug] Initial Request for bucket Rate limit bucket [GET::::/gateway/bot] [0/0] 01/01/0001 00:00:00 +00:00. Allowing.
[2019-06-05 22:03:21 +00:00] [REST] [Debug] Initial Request for bucket Rate limit bucket [GET::::/users/:user_id] [0/0] 01/01/0001 00:00:00 +00:00. Allowing.
[2019-06-05 22:03:22 +00:00] [REST] [Debug] Initial Request for bucket Rate limit bucket [GET::::/oauth2/applications/:application_id] [0/0] 01/01/0001 00:00:00 +00:00. Allowing.
[2019-06-05 22:03:22 +00:00] [REST] [Debug] Initial Request for bucket Rate limit bucket [GET::::/voice/regions] [0/0] 01/01/0001 00:00:00 +00:00. Allowing.
[2019-06-05 22:03:23 +00:00] [Websocket] [Debug] Received OP 10 (HELLO) - Trying to either resume or identify.
[2019-06-05 22:03:23 +00:00] [Websocket] [Debug] Starting Heartbeat.
[2019-06-05 22:03:23 +00:00] [Websocket] [Debug] Sending Heartbeat.
[2019-06-05 22:03:23 +00:00] [Websocket] [Debug] Received WebSocket Heartbeat Ack. Ping: 203ms
[2019-06-05 22:03:24 +00:00] [Websocket] [Error] Socket swallowed an exception:
System.MemberAccessException: Type initializer was not callable.
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|60_1(SocketMessageEventArgs e)

// A message was sent in Discord guild that the bot belongs to
[2019-06-05 22:03:39 +00:00] [Event] [Warning] Could not find channel last message belonged to.
```
# Steps to reproduce
1. write some nice bots using DSharpPlus :^)
2. Enable internal logging feature
3. Run it on Linux ARM64 build of .NET Core Preview 5? Not sure if this happens on Linux x64 as well. It didn't happen on Windows x64 builds.
4. Observe the exceptions being logged.

# Notes
Will update once I try it with .NET Core 2.2.

**Comment by WamWooWam** [comment]
Digging in, this seems to be an issue calling the constructor for a Dictionary type via reflection? Not entirely sure why this broke but it does seem like a .Net Core 3 issue

**Comment by Gnbrkm41** [comment]
[I remember trivial things like adding more overloads breaking reflection based codes.](https://github.com/dotnet/corefx/issues/31595#issuecomment-468264022)

**Comment by Gnbrkm41** [comment]
Seems to be working fine on Core 2.2 linux-arm; it just feels weird because Core 3.0 win64 worked just fine without any problem, and yet it happens on linux one.

**Comment by uwx** [comment]
what the fuck

**Comment by uwx** [comment]
Apparently a static constructor was added to the Dictionary class in Core 3.0 Why? I don't fucking know, and I don't give a damn. Anyway, so this trips up the constructor matching. I'll fix this later. If anyone wants to expediate the fix simply change the following:

https://github.com/DSharpPlus/DSharpPlus/blob/50311177aef1c0617bc45172da0d120e3fd64811/DSharpPlus/Net/Serialization/SnowflakeArrayAsDictionaryJsonConverter.cs#L37

Make it so it only searches for instance constructors. Because apparently the static one shows up there too. Fucking hell, Microsoft.

**Comment by uwx** [comment]
As to why the exception only happens in ARM64 Linux, I guess it's probably because the version on Docker is either newer or older than the one you test on. Don't think too hard about it.

**Comment by Quahu** [comment]
This is why you should always be using BindingFlags. See https://docs.microsoft.com/en-us/dotnet/api/system.type.getconstructors#System_Type_GetConstructors_System_Reflection_BindingFlags_

**Comment by uwx** [comment]
I know what BindingFlags is, Einstein. I however did not (at the time of writing that code) know static constructors were treated the same as instance ones at runtime.

**Comment by uwx** [comment]
Also, the method you linked does not exist in Standard 1.1, which is why this whole thing is so annoying to begin with. In fact, there is no BindingFlags in Standard 1.1, as far as I know. `GetDeclaredMethod` with `.ctor` might work, but that sounds like a horrible solution.

**Comment by Quahu** [comment]
Hm, what about filtering out the static constructors from what DeclaredConstructors returns?

**Comment by uwx** [comment]
That's the correct solution as far as I can tell, yeah.

**Comment by WamWooWam** [comment]
As a note, I've never been able to repro this bug using .NET Core 3 Preview 6+ on `linux-arm64`...

**Comment by uwx** [comment]
I repro'd this, but that was on a previous version (I think Preview 5?). The API might have changed a bit since.

**Comment by Emzi0767** [comment]
While there is a point to be made for fixing this so it doesn't occur for potential future API changes, preview versions are just that - previews. They might change, and we never guaranteed the library to work with preview versions of .NET Core.

Ultimately, someone should fix it, but it is not a high priority issue. If the issue persists, downgrade to .NET Core 2.2 if possible.

**Comment by Gnbrkm41** [comment]
Note that Preview 7 and 8 are production ready ("Go Live") - `NET Core 3.0 Preview 8 is supported by Microsoft and can be used in production. We strongly recommend that you test your app running on Preview 8 before deploying Preview 8 into production. `

**Comment by Gnbrkm41** [comment]
Even if we disregard the fact that it's a bug, it'll be released in the .NET Conf (2019-09-23 ~ 2019-09-25) - which is about 37 days from now. So, from then it's not really a preview only bug anymore 😅

**Comment by WamWooWam** [comment]
But by the same token, considering the bug was fixed by preview 6, it’s not really a bug anymore either.

**Comment by Emzi0767** [comment]
> Note that Preview 7 and 8 are production ready ("Go Live") -

Except:

> **We strongly recommend that you test your app running on Preview 8 before deploying Preview 8 into production.**

We will worry about Core 3 bugs when Core 3 leaves preview.

**Comment by red031000** [comment]
while testing issue #477 I also came across a `System.MemberAccessException` on linux x64, by calling DiscordClient.GetGuildAsync, more info about my setup is in that issue.

full stack trace:

```Type initializer was not callable.
   at System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at DSharpPlus.Net.DiscordApiClient.GetGuildAsync(UInt64 guildId)
   at DSharpPlus.DiscordClient.GetGuildAsync(UInt64 id)
   at StreamFeedBot.Utils.AnnounceMessage(String message, DiscordClient client) in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Utils.cs:line 66
   at StreamFeedBot.Program.MainAsync() in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 169
   at StreamFeedBot.Program.Main() in D:\TwitchPlaysPokemon\StreamFeedBot\StreamFeedBot\Program.cs:line 50```
