### ISSUE TITLE
GetAssetsAsync() thrown KeyNotFoundException.

### ISSUE THREAD

**Issue by nathan130200** [DSharpPlus/DSharpPlus#455]
# Summary
I have rich presence assets from my application, i tried to get all by D#+

# Details
Using .NET Core 2.2 and D#+ 4.0.0-nightly-00614

Well [DiscordApiClient.cs#L1884](https://github.com/DSharpPlus/DSharpPlus/blob/748f7e774c7c0f8a2ce1caa7cb36f958dd44ff6f/DSharpPlus/Net/DiscordApiClient.cs#L1884)

```
System.Collections.Generic.KeyNotFoundException: The given key 'application_id' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at DSharpPlus.Net.RestClient.GetBucket(RestRequestMethod method, String route, Object route_params, String& url)
   at DSharpPlus.Net.DiscordApiClient.GetApplicationAssetsAsync(DiscordApplication application)
   at DSharpPlus.Entities.DiscordApplication.GetAssetsAsync()
   at CSharp.Modules.DiscordModule.Assets(CommandContext ctx) in C:\Users\Nathan Ferreira\Documents\Visual Studio 2019\Projects\CSharpBot\CSharpBot\Modules\DiscordModule.cs:line 24
```

# Steps to reproduce
```cs
[Command]
public async Task Assets(CommandContext ctx)
{
	await ctx.TriggerTypingAsync();

	try
	{
		var assets = await ctx.Client.CurrentApplication.GetAssetsAsync();
		await ctx.RespondAsync($"{ctx.User.Mention} Count: {assets.Count}");
	}
	catch(Exception ex)
	{
		await ctx.RespondAsync($"{ctx.User.Mention} :x: {ex.ToString()}");
	}
}
```

**Comment by Emzi0767** [comment]
Looks like route formatting bug, possibly a refactor leftover. I'll look into this later today.
________________________________
