### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Hulkstance** [DSharpPlus/DSharpPlus#476]
# Summary
`Object reference not set to an instance of an object` occurs when I'm trying to `SendMessageAsync` from two recurring jobs at same time.
![image](https://user-images.githubusercontent.com/33224919/66896494-92ca3300-effd-11e9-9aaa-03fd01c901ba.png)
Is that rate limit issue?

# Details
Tested over ASP.NET Core 3.0.

NotificationService.cs:
```
public class NotificationService : INotificationService
{
	private DiscordClient _client;
	private readonly ILogger _logger;
	private readonly IConfiguration _configuration;

	public NotificationService(ILogger<NotificationService> logger, IConfiguration configuration)
	{
		_logger = logger;
		_configuration = configuration;
	}

	public async Task RunAsync()
	{
		_client = new DiscordClient(new DiscordConfiguration()
		{
			Token = _configuration.GetValue<string>("DiscordBot:Token"),
			TokenType = TokenType.Bot,

			AutoReconnect = true,
			EnableCompression = true,
			UseInternalLogHandler = true
		});

		_client.MessageCreated += async e =>
		{
			if (e.Message.Content.ToLower().StartsWith("test"))
				await e.Message.RespondAsync("Bot is working!");
		};

		await _client.ConnectAsync();
	}

	public async Task SendMessageAsync(string msg)
	{
		try
		{
			var channel = await _client.GetChannelAsync(_configuration.GetValue<ulong>("DiscordBot:ChannelId"));
			await channel.SendMessageAsync(msg);
		}
		catch (Exception ex)
		{
			_logger.LogError(ex.Message); // it throws it here
		}
	}

	public void Dispose()
	{
		if (_client != null)
		{
			_client.Dispose();
		}
	}
}
```

BotProcessingService.cs
```
using Binance.Interfaces;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace Binance.Services
{
    public class BotProcessingService : IBotProcessingService
    {
        private readonly ILogger _logger;
        private readonly IBotService _botService;
        private readonly INotificationService _notificationService;

        public BotProcessingService(ILogger<BotHostedService> logger, IBotService botService, INotificationService notificationService)
        {
            _logger = logger;
            _botService = botService;
            _notificationService = notificationService;
        }

        public void Execute(string botName)
        {
            ExecuteAsync(botName).Wait();
        }

        public async Task ExecuteAsync(string botName)
        {
            var bot = await _botService.GetByNameAsync(botName);

            _logger.LogError($"{bot.Name} is working. Current time: {DateTime.Now.ToLocalTime()}");
            await _notificationService.SendMessageAsync($"Bot report... Symbol: {bot.CryptoPair.Description}, Interval: {bot.TimeInterval.Description}");
        }
    }
}
```

BotHostedService.cs
```
using Binance.Interfaces;
using Hangfire;
using Hangfire.Storage;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Binance.Services
{
    public class BotHostedService : IHostedService
    {
        private readonly ILogger _logger;
        private readonly IServiceProvider _serviceProvider;

        public BotHostedService(ILogger<BotHostedService> logger, IServiceProvider serviceProvider)
        {
            _logger = logger;
            _serviceProvider = serviceProvider;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Bot service is starting.");

            RemoveAllHangfireJobs();
            _logger.LogInformation("Removed all hangfire jobs.");

            using var scope = _serviceProvider.CreateScope();
            var botService = scope.ServiceProvider
                .GetRequiredService<IBotService>();
            var notificationService = scope.ServiceProvider
               .GetRequiredService<INotificationService>();
            var botProcessingService = scope.ServiceProvider
               .GetRequiredService<IBotProcessingService>();

            // Run notification service
            await notificationService.RunAsync();

            var bots = await botService.GetAllAsync();

            foreach (var bot in bots)
            {
                if (!bot.Status)
                    continue;

                _logger.LogInformation($"{bot.Name} is starting. Symbol: {bot.CryptoPair.Description}, Interval: {bot.TimeInterval.Description}");
                RecurringJob.AddOrUpdate(bot.Name, () => botProcessingService.Execute(bot.Name), $"0/5 * * * *", TimeZoneInfo.Local);
            }
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Bot service is stopping.");

            using var scope = _serviceProvider.CreateScope();
            var botService = scope.ServiceProvider
                .GetRequiredService<IBotService>();

            var bots = await botService.GetAllAsync();

            foreach (var bot in bots)
            {
                _logger.LogInformation($"{bot.Name} is stopping.");
                RecurringJob.RemoveIfExists(bot.Name);
            }
        }

        private void RemoveAllHangfireJobs()
        {
            var monitor = JobStorage.Current.GetMonitoringApi();

            // RecurringJobs
            JobStorage.Current.GetConnection().GetRecurringJobs().ForEach(e => RecurringJob.RemoveIfExists(e.Id));

            // ProcessingJobs
            monitor.ProcessingJobs(0, int.MaxValue).ForEach(e => BackgroundJob.Delete(e.Key));

            // ScheduledJobs
            monitor.ScheduledJobs(0, int.MaxValue).ForEach(e => BackgroundJob.Delete(e.Key));

            // EnqueuedJobs
            monitor.Queues().ToList().ForEach(e => monitor.EnqueuedJobs(e.Name, 0, int.MaxValue).ForEach(x => BackgroundJob.Delete(x.Key)));
        }
    }
}
```
and two of these:
```
RecurringJob.AddOrUpdate(bot.Name, () => botProcessingService.Execute(bot.Name), $"0/5 * * * *", TimeZoneInfo.Local);
```

Stack trace:
```
   at DSharpPlus.Net.RestClient.<>c__DisplayClass20_0.<GetBucket>b__0(RateLimitBucket xb)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at DSharpPlus.Net.RestClient.GetBucket(RestRequestMethod method, String route, Object route_params, String& url)
   at DSharpPlus.Net.DiscordApiClient.<CreateMessageAsync>d__39.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Binance.Services.NotificationService.<SendMessageAsync>d__5.MoveNext() in C:\project\back-end\Binance\Services\NotificationService.cs:line 48
```

**Comment by Emzi0767** [comment]
Post full stack trace and preferably textual form of your snippet, as well as any other relevant information.

**Comment by Hulkstance** [comment]
Edited my question with it.

**Comment by Emzi0767** [comment]
It looks like you're trying to send a message before the client is fully initialized, when exactly are you calling your method?
________________________________

**Comment by Hulkstance** [comment]
It was called in another IHostedService which was executed before all that. However, I moved it in `BotHostedService.cs`, will add the code in the question.

**Comment by Emzi0767** [comment]
Yeah looking at it, the first send is fired before the client is done initializing.

Wait for the guild download completed event, or at the very least, ready event before performing any such operations.

**Comment by Hulkstance** [comment]
```
public async Task RunAsync()
{
	_client = new DiscordClient(new DiscordConfiguration()
	{
		Token = _configuration.GetValue<string>("DiscordBot:Token"),
		TokenType = TokenType.Bot,

		AutoReconnect = true,
		EnableCompression = true,
		UseInternalLogHandler = true
	});

	_client.MessageCreated += async e =>
	{
		if (e.Message.Content.ToLower().StartsWith("test"))
			await e.Message.RespondAsync("Bot is working!");
	};

	_client.Ready += OnReadyAsync; // Note that line

	await _client.ConnectAsync();
}

private async Task OnReadyAsync(ReadyEventArgs e)
{
	await Task.Yield();
}
```

Just like that?

**Comment by Emzi0767** [comment]
Because you're not doing anything to prevent it from happening. You need to block any sends before you get the Ready event.

**Comment by Hulkstance** [comment]
It's weird. I did that in the code below and for more than one hour it didn't fail. The weird part is that `_logger.LogWarning("Client not initialized yet and SendMessageAsync was called.");` was never shown.

```
public async Task RunAsync()
{
	_client = new DiscordClient(new DiscordConfiguration()
	{
		Token = _configuration.GetValue<string>("DiscordBot:Token"),
		TokenType = TokenType.Bot,

		AutoReconnect = true,
		EnableCompression = true,
		UseInternalLogHandler = true
	});

	_client.MessageCreated += async e =>
	{
		if (e.Message.Content.ToLower().StartsWith("test"))
			await e.Message.RespondAsync("Bot is working!");
	};

	_client.Ready += OnReadyAsync;

	await _client.ConnectAsync();
}

private async Task OnReadyAsync(ReadyEventArgs e)
{
	await Task.Yield();
	IsReady = true;
}

public async Task SendMessageAsync(string msg)
{
	if (IsReady)
	{
		try
		{
			var channel = await _client.GetChannelAsync(_configuration.GetValue<ulong>("DiscordBot:ChannelId"));
			await channel.SendMessageAsync(msg);
		}
		catch (Exception ex)
		{
			_logger.LogError(ex.Message);
		}
	}
	else
	{
		_logger.LogWarning("Client not initialized yet and SendMessageAsync was called.");
	}
}
```

**Comment by Emzi0767** [comment]
Could be a timing issue.

**Comment by Hulkstance** [comment]
You were right that this is the reason, but why wouldn't `if (IsReady)`'s else statement execute?

**Comment by Emzi0767** [comment]
I do not know
________________________________

**Comment by Hulkstance** [comment]
I think it's really the rate limit stuff.

**Comment by WamWooWam** [comment]
Well, like, generally boolean values aren't a great way to handle race conditions, which is what you're experiencing here. If there was a major bug like this in the rate limit system I'm 99% sure we'd have more than one report :P

Rate limit buckets are initialised when you connect to Discord, so I'm almost certain your client isn't initialised properly at the point you're calling `SendMessageAsync`.

One thing I've noticed is that you're always constructing a new client whenever your service runs, which means if it's already initialised (which it quite possibly is), you're overwriting with a new uninitialized client. Ready will already have fired on the previous client, and `IsReady` would be true, but because you've overwritten the client, it wouldn't be accurate. See here:

```cs
public async Task RunAsync()
{
    _client = new DiscordClient(new DiscordConfiguration()
    {
        Token = _configuration.GetValue<string>("DiscordBot:Token"),
        TokenType = TokenType.Bot,

        AutoReconnect = true,
        EnableCompression = true,
        UseInternalLogHandler = true
    });
    -snip-
}
```

I suggest adding a check to ensure `_client` hasn't been initialised already come the call of `RunAsync`.

Another thing I have noticed is some very bad async code which may be causing some problems:
> ```cs
> public void Execute(string botName)
> {
>    ExecuteAsync(botName).Wait();
> }
> ```

Generally speaking, you should *never* use `.Wait()` on a `Task`.

**Comment by Hulkstance** [comment]
Looks like it's not possible in this way because of the rate limit (at least I don't have other explanation). I switched to WebHooks for that case. I hope it helps anyone else who wants to implement a Discord Notification System.
