### ISSUE TITLE
how to set a default command for [Group]?

### ISSUE THREAD

**Issue by unlimitedcoder2** [DSharpPlus/DSharpPlus#665]
# Summary
How do I set the default command to execute in a group?
for example
```
!bio @User // will run the default
!bio set New bio // will run the set command
```
# Details

```cs
	[Group("bio")]
	public class BioModule
	{
		[Command("")]
		[Description("Get a users bio")]
		[Cooldown(2, 3d, CooldownBucketType.User)]
		public async Task GetUserBio(CommandContext ctx, [Description("User to get bio of")] DiscordUser user)
		{
			await ctx.RespondAsync(embed: new DiscordEmbedBuilder().AddField("Hello", "World").Build());
		}

		[Command("set")]
		[Description("Set your bio")]
		[Cooldown(1, 300d, CooldownBucketType.User)]
		public async Task SetBio(CommandContext ctx, [Description("")] string bio)
		{
			await ctx.RespondAsync("Set your bio to stuff");
		}
	}
}
```

```log
Unhandled exception. DSharpPlus.CommandsNext.Exceptions.DuplicateCommandException: A command with a given name already exists.
   at DSharpPlus.CommandsNext.CommandsNextModule.AddToCommandDictionary(Command cmd)
   at DSharpPlus.CommandsNext.CommandsNextModule.RegisterCommands(Type t)
```

**Comment by Speyd3r** [comment]
You need the [GroupCommand] Attribute there
Its essentially Command("") for Groupcommands

**Comment by Emzi0767** [comment]
It's not like that info is available in docs and examples...

**Comment by unlimitedcoder2** [comment]
Yeah those docs are clearly kept up to date
![image](https://user-images.githubusercontent.com/16884313/98553660-c1b1e780-2297-11eb-96ab-a520b467890e.png)

**Comment by Emzi0767** [comment]
Your inability to use correct docs correctly doesn't make them bad.

**Comment by unlimitedcoder2** [comment]
Docs clearly are correct
![image](https://user-images.githubusercontent.com/16884313/98554447-a398b700-2298-11eb-8d6f-9a5c214e22ad.png)

**Comment by Emzi0767** [comment]
> Your inability to use correct docs correctly doesn't make them bad.

Use correct docs for your library version.
