### ISSUE TITLE
GetMessagesAsync can't handle pin notification messages.

### ISSUE THREAD

**Issue by ikegami** [DSharpPlus/DSharpPlus#749]
`GetMessagesAsync` can't handle pin notification messages ("User pinned a message to this channel").

Using: 4.0.0-nightly-00786

Code:

```csharp
var msgs = await channel.GetMessagesAfterAsync(700405431994155089, 1);
```
                
The message (700577204555350046) after the specified message (700405431994155089):

![A pin notifaction](https://user-images.githubusercontent.com/699749/106571178-d7d0ec00-6504-11eb-87ee-39311c745817.png)

Response:

```json
[
  {
    "id": "700577204555350046",
    "type": 6,
    "content": "",
    "channel_id": "302432047253815296",
    "author": {
      "id": "92074579006083072",
      "username": "Persona",
      "avatar": "8f22eb3090d63a937a1712c16578a255",
      "discriminator": "4216",
      "public_flags": 0
    },
    "attachments": [],
    "embeds": [],
    "mentions": [],
    "mention_roles": [],
    "pinned": false,
    "mention_everyone": false,
    "tts": false,
    "timestamp": "2020-04-17T05:23:41.661000+00:00",
    "edited_timestamp": null,
    "flags": 0,
    "message_reference": {
      "channel_id": "302432047253815296",
      "guild_id": "90897972715352064",
      "message_id": "700577091720183818"
    }
  }
]
```

Result:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DSharpPlus
  StackTrace:
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.<GetChannelMessagesAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DSharpPlus.Entities.DiscordChannel.<GetMessagesInternalAsync>d__76.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TTSClubSaveMover.Program.<Job>d__19.MoveNext() in C:\Users\ikegami\Home\Projects\Tabletop Simulator\ttsclub_bot\save_mover\Program.cs:line 199

  This exception was originally thrown at this call stack:
    [External Code]
    TTSClubSaveMover.Program.Job() in Program.cs
```

**Comment by VelvetThePanda** [comment]
I can't seem to repro; am I missing something? https://velvet.is-ne.at/Qam3eT.png

**Comment by VelvetThePanda** [comment]
I can try with get messages after, though

**Comment by Neuheit** [comment]
I can reproduce it with `GetMessagesAfter`, I have a fix for it just waiting on a response.

**Comment by VelvetThePanda** [comment]
Ah. Even with `GetMessagesAfter`, I can't seem to repo in 786 ![](https://velvet.is-ne.at/UOH9oR.png)

**Comment by VelvetThePanda** [comment]
Nevermind, turns out I copied the wrong message Id. Same error. Odd, though
