### ISSUE TITLE
`DiscordChannel.GetMessagesAsync` throws exception when encountering a reply to a deleted message

### ISSUE THREAD

**Issue by ikegami** [DSharpPlus/DSharpPlus#799]
`DiscordChannel.GetMessagesAsync` throws exception when it encounters a reply to a deleted message.

Code:

```csharp
var msgs = await channel.GetMessagesAsync(100);
```

Channel's entire contents:

![Channel with reply to a deleted a message, a reply to an existing message, and that message](https://user-images.githubusercontent.com/699749/111902096-04d45200-8a12-11eb-8d91-13c312a3e4dc.png)

Result:

```
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at DSharpPlus.Net.DiscordApiClient.PrepareMessage(JToken msg_raw)
   at DSharpPlus.Net.DiscordApiClient.GetChannelMessagesAsync(UInt64 channel_id, Int32 limit, Nullable`1 before, Nullable`1 after, Nullable`1 around)
   at DSharpPlus.Entities.DiscordChannel.GetMessagesInternalAsync(Int32 limit, Nullable`1 before, Nullable`1 after, Nullable`1 around)
   at [above call]
```

The problem goes away if I delete the bottom message.

**Comment by ikegami** [comment]
I'm using the latest nightly build (816).

**Comment by ikegami** [comment]
Thanks for the quick fix.

**Comment by Neuheit** [comment]
No problem!
