### ISSUE TITLE
Trying to set bot's username/avatar results in HttpException: 400 BadRequest

### ISSUE THREAD

**Issue by JOBBIN9422** [DSharpPlus/DSharpPlus#802]
# Summary
Trying to set the bot's username and/or avatar via `ModifyAsync` on its current user object throws an HttpException: `400 BadRequest`.
```csharp
[Command("reset", RunMode = RunMode.Async)]
[Summary("Reset the bot's avatar and nickname.")]
public async Task ResetBotAvatarAndUsername()
{
    await _bot.Client.CurrentUser.ModifyAsync(x =>
    {
        x.Username = "Terminus.NET";
        x.Avatar = new Image(Path.Combine("assets", "images", "terminus.jpg"));
    });
}
```
# Details
- .NET version: `5.0`
- Discord.NET version: `2.3.1`

Stack trace:
```
Discord.Net.HttpException: The server responded with error 400: BadRequest
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.ModifySelfAsync(ModifyCurrentUserParams args, RequestOptions options)
   at Discord.Rest.UserHelper.ModifyAsync(ISelfUser user, BaseDiscordClient client, Action`1 func, RequestOptions options)
```

# Steps to reproduce
1. Modify a bot user's avatar or username via `ModifyAsync`

# Notes
- Sometimes, the request does not get a response for several minutes. 
- Sometimes, the nickname is set but the avatar is never updated.
- The image I'm attempting to use is 8.9KB (300 x 204).

**Comment by Neuheit** [comment]
This is a Discord.Net issue, not DSharpPlus.
