### ISSUE TITLE
InvalidOperationException thrown for attempting to delete a nonexistent role despite no operation to do so.

### ISSUE THREAD

**Issue by SeraphimRP** [DSharpPlus/DSharpPlus#948]
# Summary
For some reason, an InvalidOperationException is thrown for attempting to delete a nonexistent role. My code contains no logic to delete a role, so I'm presuming that this is a bug internally.

# Details
- **OS**: Amazon Linux 2
- **.NET Core Version**: 5.0.6
- **DSharpPlus Version**: 4.1.0-nightly-00879

Traceback:
```
[2021-06-19 11:25:11 +00:00] [108 /WebSocketRec] [Error] Socket handler suppressed an exception
System.InvalidOperationException: Attempted to delete a nonexistent role.
at DSharpPlus.DiscordClient.OnGuildRoleDeleteEventAsync(UInt64 roleId, DiscordGuild guild)
at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|369_1(IWebSocketClient sender, SocketMessageEventArgs e)
```

# Steps to reproduce
???

**Comment by IDoEverything** [comment]
Are you hooking the `GuildRoleDeleted` event anywhere?

**Comment by SeraphimRP** [comment]
Nope. I'm hooking:

- `SocketOpened` and `SocketClosed` for logging connection changes
- `Ready` for presence and logging that
- `Resumed` for logging,
- `MessageCreated`
- `GuildCreated` and `GuildDeleted` for server count tracking.
