### ISSUE TITLE
Error setting value to 'AvatarHash' on 'DSharpPlus.Entities.DiscordMember'.

### ISSUE THREAD

**Issue by ChrisonSimtian** [DSharpPlus/DSharpPlus#972]
I have one server where this happens straight after starting the bot
I suspect it happens during DiscordClient.GuildAvailable fires for that specific server (or whatever method is running in behind)
I'll try to debug through it and find out more, but I just stumbled across this :-)

edit: seems to be related to this?
https://github.com/DSharpPlus/DSharpPlus/issues/913
cant confirm since I dont have nitro to test it and no access to their server :-(

[2021-07-03 13:16:00 +12:00] [101 /Startup     ] [Info ] DSharpPlus, version 4.0.1
[2021-07-03 13:16:03 +12:00] [108 /WebSocketRec] [Error] Socket handler suppressed an exception
Newtonsoft.Json.JsonSerializationException: Error setting value to 'AvatarHash' on 'DSharpPlus.Entities.DiscordMember'.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.Entities.DiscordMember.get_User()
   at DSharpPlus.Entities.DiscordMember.set_AvatarHash(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at DSharpPlus.Net.Serialization.SnowflakeArrayAsDictionaryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at DSharpPlus.DiscordClient.HandleDispatchAsync(GatewayPayload payload)
   at DSharpPlus.DiscordClient.HandleSocketMessageAsync(String data)
   at DSharpPlus.DiscordClient.<InternalConnectAsync>g__SocketOnMessage|365_1(IWebSocketClient sender, SocketMessageEventArgs e)

**Comment by DWaffles** [comment]
What version of D#+ are you using? If I recall correctly, the fix was implemented several nightly versions ago.

**Comment by VelvetThePanda** [comment]
@ChrisonSimtian this is an issue related to per-server avatars and the serializer attempting to set the per-server avatar on the user object which isn't constructed at serialization time (as well as being the wrong object to put it on). This issue was fixed in #913, and any build after ~870(?) should work I believe. If you aren't already, you'll wanna update to the latest nightly, which also has various other bug fixes.

**Comment by ChrisonSimtian** [comment]
Hey thanks, forgot to hit the send button on my last comment...
I was using 4.0.1 and updated to the latest nightly in order to "fix" it :-)
Can be marked as resolved/duplicate to #913

**Comment by Neuheit** [comment]
As mentioned above this issue was already fixed in the nightlies, however I will be pushing a stable version to nuget soon.

**Comment by ChrisonSimtian** [comment]
Sweet bro, let me know when, I'll test and confirm for you. Would be große Neuigkeiten for me to have that on a stable release :-)
